### ISSUE TITLE
Replace jonathantneal/polyfill with other library

### ISSUE THREAD

**Issue by monolithed** [azproduction/autopolyfiller-stable#1]
Please replace [jonathantneal/polyfill](https://github.com/jonathantneal/polyfill) with other library.
The one does not work as should.....

For example: [Object.create](https://github.com/jonathantneal/polyfill/blob/master/source/Object.create.js), [Promise](https://github.com/jonathantneal/polyfill/blob/master/source/Promise.js),  [String.prototype.trim](https://github.com/jonathantneal/polyfill/blob/master/source/String.prototype.trim.js) etc

**Comment by azproduction** [comment]
@monolithed do you have any stable sources?
Financial-Times's clone of polyfill is pretty much the same as jonathantneal/polyfill // cc @samgiles

**Comment by samgiles** [comment]
So, yes, we're in the process of testing these polyfills and are encouraging contributions. This week, probably today or tomorrow we will have a full testing infrastructure in place that will test and produce reports for as many browsers as SauceLabs have.  We should then be able to slowly improve the quality based on community contribution and extensive testing.  I guess we're still early on with this service so it will certainly improve in the next few months.  Stick with us!

**Comment by monolithed** [comment]
@azproduction, 
https://github.com/es-shims/es5-shim // @es-shims
https://github.com/paulmillr/es6-shim/  // @paulmillr

looks good and well tested

@samgiles, looks better than a well, but also there are bugs like:

``` js
// bad
Object.create(null); // TypeError: Object prototype may only be an Object or null
Object.create({}, null); // Object {}

// must be
Object.create(null); // Object {}
Object.create(null).toString; // undefined 
Object.create({}, null); // TypeError: Cannot convert undefined or null to object
// etc
```

In truth, with `Object.create` is not a very good example, because I do not know how to implement it IE without `__proto__` :)

**Comment by termi** [comment]
The main benefit of the [es5/es6](https://github.com/es-shims) libs is a big community and more then 2 years of developments. @monolithed I suggest you not to use https://github.com/azproduction/autopolyfiller-stable. Because of the problem you mentioned this lib is useless.

**Comment by azproduction** [comment]
See https://github.com/azproduction/autopolyfiller/issues/18
